### ISSUE TITLE
basejump_stl/bsg_noc/bsg_wormhole_router_generalized.v missing

### ISSUE THREAD

**Issue by browygit** [bespoke-silicon-group/bsg_manycore#555] opened 2021-08-03 17:59 UTC
Hi,

We are getting compile error when running the bsg_manycore testbench using 

bsg_manycore/testbenches/manycore_loopback_ddr_link/filelist

 71 $BASEJUMP_STL_DIR/bsg_noc/bsg_wormhole_router_generalized.v

file is missing.  Can we safely point to the bsg_wormhole_router.v instead?

Thanks

**Comment by gaozihou** [comment] 2021-08-03 19:10
Yeah this testbench is not up-to-date, should be okay to point to https://github.com/bespoke-silicon-group/basejump_stl/blob/master/bsg_noc/bsg_wormhole_router.v

**Comment by dpetrisko** [comment] 2021-08-03 19:24
Note the parameter interface has changed slightly, so there will need to be some minor updates to the instantiation as well

**Comment by browygit** [comment] 2021-08-03 20:30
OK thanks.  So just to summarize we'll edit
testbenches/manycore_loopback_ddr_link/bsg_manycore_loopback_ddr_link_tester.v
to instance bsg_wormhole_router module instead of bsg_wormhole_router_generalized and edit filelist to point to the file you noted above.

**Comment by Kelin9298** [comment] 2021-08-06 07:08
Hi, 

After I modified the filelist and the bsg_manycore_loopback_ddr_link_tester.v like above, I got this error
====
Error-[SV-LCM-PND] Package not defined
../../v/bsg_manycore_link_async_to_wormhole.v, 13
bsg_manycore_link_async_to_wormhole, "bsg_manycore_pkg::"
  Package scope resolution failed. Token 'bsg_manycore_pkg' is not a package.
  Originating module 'bsg_manycore_link_async_to_wormhole'.
  Move package definition before the use of the package.

Error-[UM] Undefined macro
../../v/bsg_manycore_link_async_to_wormhole.v, 31
  Undefined macro exists as: 'bsg_manycore_link_sif_width'
  "../../v/bsg_manycore_link_async_to_wormhole.v", 31: token is
  '`bsg_manycore_link_sif_width'
    ,localparam bsg_manycore_link_sif_width_lp =
  `bsg_manycore_link_sif_width(addr_width_p,data_width_p,x_cord_width_p,y_cord_width_p)
                                                                             ^
====

Any ideal how to solve this problem?

**Comment by dpetrisko** [comment] 2021-08-06 07:15
Add bsg_manycore_pkg to the filelist

**Comment by Kelin9298** [comment] 2021-08-06 07:31
Hi thanks, it worked, but another error:

Error-[SFCOR] Source file cannot be opened
  Source file "bsg_manycore_packet.vh" cannot be opened for reading due to 'No
  such file or directory'.

I don't find this file

**Comment by dpetrisko** [comment] 2021-08-06 08:12
I would replace `include "bsg_manycore_packet.vh" with import bsg_manycore_pkg::*; in the testbench files

**Comment by Kelin9298** [comment] 2021-08-06 08:26
Hi another error
```
Error-[MAM] Macro argument number mismatch
./bsg_manycore_loopback_ddr_link_tester.v, 168
  Macro argument number mismatch for macro 'declare_bsg_manycore_link_sif_s'
  "./bsg_manycore_loopback_ddr_link_tester.v", 168 (expanding macro
  'declare_bsg_manycore_link_sif_s'): token is ')', column 123
    `declare_bsg_manycore_link_sif_s
  (mc_addr_width_p,mc_data_width_p,mc_x_cord_width_p,mc_y_cord_width_p,mc_load_id_width_p);
  Location of macro 'declare_bsg_manycore_link_sif_s' definition:
  ../../v/bsg_manycore_pkg.v, 164
```

**Comment by dpetrisko** [comment] 2021-08-06 08:28
I would look at the rest of the code base and update the macros with the correct parameters, as used in the main code

**Comment by Kelin9298** [comment] 2021-08-06 08:44
Hi thanks,

I've updated the rest macros, and then it ends like this
```
Note-[SV-LCM-PPWI] Package previously wildcard imported
./bsg_manycore_loopback_test_node.v, 2
$unit
  Package 'bsg_manycore_pkg' already wildcard imported.
  Ignoring bsg_manycore_pkg::*
  See the SystemVerilog LRM(1800-2005), section 19.2.1.

1 warning
4 errors
```
Is there any log files that logged the errors?

**Comment by taylor-bsg** [comment] 2021-08-06 08:59
If you have trouble figuring out the issue, you can point us to a fork and we can try running your mods on our side..

**Comment by Kelin9298** [comment] 2021-08-09 09:48
Hi, 

I've tried the latest update, an assertion failure appeared before I got any error related to bsg_wormhole_router_generalized.v
```
Back to file '../../../basejump_stl/bsg_misc/bsg_circular_ptr.v'.

Error-[SE] Syntax error
  Following verilog source has syntax error :
  	Using deferred assertion requires an option -assert svaext
  "../../../basejump_stl/bsg_misc/bsg_circular_ptr.v", 72: token is 'final'
                assert final( (ptr_n < slots_p) || (|ptr_n === 'X) || reset_i 
  || (add_i > slots_p))
                            ^

1 error
```
I only modified this line in the manycore_loopback_ddr_link/Makefile
```
#include $(BSG_CADENV_DIR)/cadenv.mk
export VCS_BIN=/edatools/vcs_O-2018.09-SP2/bin
```

**Comment by dpetrisko** [comment] 2021-08-09 09:58
Add -assert svaext to the VCS flags in the makefile

**Comment by drichmond** [comment] 2021-08-09 16:01
> Hi,
> 
> I've tried the latest update, an assertion failure appeared before I got any error related to bsg_wormhole_router_generalized.v
> 
> ```
> Back to file '../../../basejump_stl/bsg_misc/bsg_circular_ptr.v'.
> 
> Error-[SE] Syntax error
>   Following verilog source has syntax error :
>   	Using deferred assertion requires an option -assert svaext
>   "../../../basejump_stl/bsg_misc/bsg_circular_ptr.v", 72: token is 'final'
>                 assert final( (ptr_n < slots_p) || (|ptr_n === 'X) || reset_i 
>   || (add_i > slots_p))
>                             ^
> 
> 1 error
> ```
> 
> I only modified this line in the manycore_loopback_ddr_link/Makefile
> 
> ```
> #include $(BSG_CADENV_DIR)/cadenv.mk
> export VCS_BIN=/edatools/vcs_O-2018.09-SP2/bin
> ```

Is this still with the aws-vcs platform?

**Comment by Kelin9298** [comment] 2021-08-10 02:18
Hi, I went to the bsg_bladerunner/bsg_manycore/testbenches/manycore_loopback_ddr_link directory, modified the Makefile and typed "make run". Does make in this place have something to do with platform? Or, will running just one testcase like this work?

**Comment by taylor-bsg** [comment] 2021-08-10 03:03
@Kelin9298 Perhaps you can tell us a little about what you are trying to accomplish and we can guide you towards an approach...

**Comment by Kelin9298** [comment] 2021-08-10 06:02
Hi, I'm trying to take out bsg_manycore and run regression on manycore, thanks

**Comment by taylor-bsg** [comment] 2021-08-10 08:37
Okay I see -- then you just need to checkout just bsg_manycore, and then follow the readme. The regression tests are in the software directory. The bsg_manycore/testbenches/manycore_loopback_ddr_link directory is not a core test.

**Comment by Kelin9298** [comment] 2021-08-10 09:38
Hi, I have no access to the cadenv.mk, I can only comment out the line that includes cadenv.mk, and export VCS_HOME. Now I am doing the make machines step, but it terminated Errors and showed messages like
```
-l pod_4x4/build.log -Mdir=pod_4x4/csrc
/bin/sh: v2k: command not found
/bin/sh: v2k: command not found
make[1]: *** [pod_1x1_hbm2/simv] Error 127
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [pod_1x1/simv] Error 127
/bin/sh: v2k: command not found
make[1]: *** [pod_4x4/simv] Error 127
make[1]: Leaving directory `/home/qemudemo/bsg_products/bsg_manycore_test/bsg_manycore/machines'
make: *** [machines] Error 2
```
Do you know how to solve this one? Thanks

**Comment by Kelin9298** [comment] 2021-08-10 09:39
Hi, I have no access to the cadenv.mk, I can only comment out the line that includes cadenv.mk, and export VCS_HOME. Now I am doing the make machines step, but it terminated Errors and showed messages like
```
-l pod_4x4/build.log -Mdir=pod_4x4/csrc
/bin/sh: v2k: command not found
/bin/sh: v2k: command not found
make[1]: *** [pod_1x1_hbm2/simv] Error 127
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [pod_1x1/simv] Error 127
/bin/sh: v2k: command not found
make[1]: *** [pod_4x4/simv] Error 127
```
Do you know how to solve this one? Thanks

**Comment by taylor-bsg** [comment] 2021-08-11 19:08
I believe you need the variable VCS to be set which is the path to the vcs binary. I checked in a check for VCS in that makefile!

**Comment by Kelin9298** [comment] 2021-08-12 07:38
Hi, thanks, I can now successfully run the regressions.

**Comment by taylor-bsg** [comment] 2021-08-13 00:12
Great let us know if you have any more questions!

**Closed** 2021-08-16 22:35 UTC

**Comment by natewise** [comment] 2022-03-24 23:31
Where are the binaries for VCS typically located? I'm getting the same error but I'm not sure where to set the path to
